# Comments are provided throughout this file to help you get started.
# If you need more help, visit the Docker Compose reference guide at
# https://docs.docker.com/go/compose-spec-reference/

# Here the instructions define your application as a service called "server".
# This service is built from the Dockerfile in the current directory.
# You can add other services your application may depend on here, such as a
# database or a cache. For examples, see the Awesome Compose repository:
# https://github.com/docker/awesome-compose
services:
  server:
    container_name: spring_backend
    build:
      context: .
    ports:
      - 50000:50000
    environment:
      - token_secret_key=${token_secret_key}
      - paseto_footer=${paseto_footer}
      
      - redis_host=${redis_host}
      - redis_port=${redis_port}
      
      - postgres_username=${postgres_username}
      - postgres_password=${postgres_password}
      - postgres_sql_url=${postgres_sql_url}
      - postgres_host=${postgres_host}
      - postgres_port=${postgres_port}
      - postgres_db=${postgres_db}
      
      - TMDB_KEY=${TMDB_KEY}
      

# The commented out section below is an example of how to define a PostgreSQL
# database that your application can use. `depends_on` tells Docker Compose to
# start the database before your application. The `db-data` volume persists the
# database data between container restarts. The `db-password` secret is used
# to set the database password. You must create `db/password.txt` and add
# a password of your choosing to it before running `docker-compose up`.
    depends_on:
      db:
        condition: service_healthy
      redis:    
        condition: service_started
    networks:
      - backend_network

  db:
    image: postgres
    restart: always
    user: postgres
    container_name: ${postgres_host}
    # secrets:
    #   - db-password
    volumes:
      - db-data:/var/lib/postgresql/data
      - ./db-init:/docker-entrypoint-initdb.d # Mount the init script correctly
    environment:
      - POSTGRES_DB=${postgres_db}
      - POSTGRES_PASSWORD=${postgres_password}
      # - POSTGRES_PASSWORD_FILE=/run/secrets/db-password
    expose:
      - 5432
    healthcheck:
      test: [ "CMD", "pg_isready" ]
      interval: 10s
      timeout: 5s
      retries: 5
    networks:
      - backend_network


  redis:
    image: redis
    container_name: ${redis_host}
    restart: always
    expose:
      - 6379
    healthcheck:
      test: ["CMD", "redis-cli", "ping"]
      interval: 10s
      timeout: 5s
      retries: 5
    networks:
      - backend_network

networks:
  backend_network:
    driver: bridge

volumes:
  db-data:
# secrets:
#   db-password:
#     file: db/password.txt

