security:
    ignored: /**
spring:
    application:
        name: streamsage
    jpa:
      show-sql: true
      hibernate:
        ddl-auto: update
    h2:
      console:
        enabled: true
    datasource:
      url: jdbc:h2:mem:testdb
server:
  port: 50000

env:
  TMDB_KEY: ${TMDB_KEY}