# This workflow will build a Java project with Maven, and cache/restore any dependencies to improve the workflow execution time
# For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-java-with-maven

# This workflow uses actions that are not certified by GitHub.
# They are provided by a third-party and are governed by
# separate terms of service, privacy policy, and support
# documentation.

name: Run Test on Push to Main

on:
  push:
    branches: [ "main", "development"]
  pull_request:
      branches: [ "main", "action-branch" ]

jobs:
  build:
    services:
        docker:
          image: docker:dind

    env:
      POSTGRES_DB: ${{ secrets.POSTGRES_DB }}
      SPRING_DATASOURCE_URL: jdbc:postgresql://localhost:5432/${{ secrets.POSTGRES_DB }}
      POSTGRES_PASSWORD: ${{ secrets.POSTGRES_PASSWORD }}
      token_secret_key: ${{secrets.TOKEN_SECRET_KEY}}
      paseto_footer: ${{secrets.PASETO_FOOTER}}

      TMDB_KEY:: ${{secrets.TMDB_KEY}}
      postgres_sql_url: ${{secrets.POSTGRES_SQL_URL}}
      DOCKER_HOST: "tcp://localhost:2375"

      SPRING_PROFILES_ACTIVE: test
      SPRING_DATASOURCE_USERNAME: ${{ secrets.POSTGRES_USER }}
      SPRING_DATASOURCE_PASSWORD: ${{ secrets.POSTGRES_PASSWORD }}

      REDIS_HOST: ${{ secrets.REDIS_HOST }}
      REDIS_PORT: ${{ secrets.REDIS_PORT }}
         
    runs-on: ubuntu-latest
    
    steps:
    - uses: actions/checkout@v4
    - name: Set up JDK 21
      uses: actions/setup-java@v4
      with:
        java-version: '21'
        distribution: 'temurin'
        cache: maven

    - name: Debug environment variables
      run: env | grep SPRING

    - name: Debug environment variables
      run: env | grep TMDB

    - name: set up docker
      run: |
        docker --version
        sudo systemctl start docker
        sleep 5

    - name: debug env var
      run: env | grep POSTGRES
    
    - name: Run Tests
      run: mvn test -X
